#!/bin/bash

VERSION=$(grep '"version": ' package.json | head | cut -d'"' -f 4)
echo "postversion: Updated version to $VERSION"

# Replace the hardcoded version string
sed -i "s/ge-tracker-api client v[^']*/ge-tracker-api client v$VERSION/g" src/lib/client.ts

# Add the version change into the previous version commit
git add src/lib/client.ts
echo git commit --amend --no-edit
echo git tag -fa "v$VERSION" -m "v$VERSION"
