name: Tests

on:
  # Run for all push commits, but not when a tag is committed
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.json'
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**.json'

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        node: [22, 24]
    uses: ./.github/workflows/service_tests.yml
    with:
      node-version: ${{ matrix.node }}
